-- AgroMotor - automatizacion hidrica diaria
-- Pronosticos, calibracion por lote, eventos de riego y ejecucion programada.

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS pg_cron;
CREATE EXTENSION IF NOT EXISTS pg_net;

CREATE TABLE IF NOT EXISTS public.hydric_forecasts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  lote_id text NOT NULL,
  run_at timestamptz NOT NULL DEFAULT now(),
  run_date date NOT NULL DEFAULT CURRENT_DATE,
  latitude double precision NOT NULL,
  longitude double precision NOT NULL,
  model text NOT NULL DEFAULT 'open-meteo-best-match',
  current_state jsonb NOT NULL DEFAULT '{}'::jsonb,
  forecast_days jsonb NOT NULL DEFAULT '[]'::jsonb,
  summary jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, lote_id, run_date)
);

CREATE INDEX IF NOT EXISTS idx_hydric_forecasts_lote_run
  ON public.hydric_forecasts (user_id, lote_id, run_at DESC);

CREATE INDEX IF NOT EXISTS idx_hydric_forecasts_created
  ON public.hydric_forecasts (created_at);

CREATE TABLE IF NOT EXISTS public.hydric_calibrations (
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  lote_id text NOT NULL,
  samples integer NOT NULL DEFAULT 0 CHECK (samples >= 0),
  bias_layers jsonb NOT NULL DEFAULT '{}'::jsonb,
  mae_layers jsonb NOT NULL DEFAULT '{}'::jsonb,
  last_error jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, lote_id)
);

CREATE TABLE IF NOT EXISTS public.hydric_latest (
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  lote_id text NOT NULL,
  forecast_id bigint REFERENCES public.hydric_forecasts(id) ON DELETE SET NULL,
  summary jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, lote_id)
);

CREATE TABLE IF NOT EXISTS public.hydric_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  lote_id text NOT NULL,
  client_event_id text NOT NULL,
  event_type text NOT NULL CHECK (event_type IN ('irrigation', 'rain_manual', 'sensor_adjustment')),
  event_at timestamptz NOT NULL DEFAULT now(),
  amount_mm numeric(8,2) NOT NULL CHECK (amount_mm >= 0 AND amount_mm <= 500),
  efficiency numeric(5,4) NOT NULL DEFAULT 1 CHECK (efficiency > 0 AND efficiency <= 1),
  effective_mm numeric(8,2) GENERATED ALWAYS AS (amount_mm * efficiency) STORED,
  source text NOT NULL DEFAULT 'user',
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, client_event_id)
);

CREATE INDEX IF NOT EXISTS idx_hydric_events_lote_date
  ON public.hydric_events (user_id, lote_id, event_at DESC);

CREATE TABLE IF NOT EXISTS public.system_secrets (
  key text PRIMARY KEY,
  secret_value text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO public.system_secrets (key, secret_value)
VALUES ('hydric_cron_token', encode(gen_random_bytes(32), 'hex'))
ON CONFLICT (key) DO NOTHING;

ALTER TABLE public.hydric_forecasts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hydric_calibrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hydric_latest ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hydric_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_secrets ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "hydric_forecasts_select_own" ON public.hydric_forecasts;
CREATE POLICY "hydric_forecasts_select_own"
  ON public.hydric_forecasts FOR SELECT TO authenticated
  USING ((select auth.uid()) = user_id);

DROP POLICY IF EXISTS "hydric_calibrations_select_own" ON public.hydric_calibrations;
CREATE POLICY "hydric_calibrations_select_own"
  ON public.hydric_calibrations FOR SELECT TO authenticated
  USING ((select auth.uid()) = user_id);

DROP POLICY IF EXISTS "hydric_latest_select_own" ON public.hydric_latest;
CREATE POLICY "hydric_latest_select_own"
  ON public.hydric_latest FOR SELECT TO authenticated
  USING ((select auth.uid()) = user_id);

DROP POLICY IF EXISTS "hydric_events_select_own" ON public.hydric_events;
CREATE POLICY "hydric_events_select_own"
  ON public.hydric_events FOR SELECT TO authenticated
  USING ((select auth.uid()) = user_id);

DROP POLICY IF EXISTS "hydric_events_insert_own" ON public.hydric_events;
CREATE POLICY "hydric_events_insert_own"
  ON public.hydric_events FOR INSERT TO authenticated
  WITH CHECK ((select auth.uid()) = user_id);

DROP POLICY IF EXISTS "hydric_events_update_own" ON public.hydric_events;
CREATE POLICY "hydric_events_update_own"
  ON public.hydric_events FOR UPDATE TO authenticated
  USING ((select auth.uid()) = user_id)
  WITH CHECK ((select auth.uid()) = user_id);

DROP POLICY IF EXISTS "hydric_events_delete_own" ON public.hydric_events;
CREATE POLICY "hydric_events_delete_own"
  ON public.hydric_events FOR DELETE TO authenticated
  USING ((select auth.uid()) = user_id);

GRANT SELECT ON public.hydric_forecasts TO authenticated;
GRANT SELECT ON public.hydric_calibrations TO authenticated;
GRANT SELECT ON public.hydric_latest TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.hydric_events TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.hydric_events_id_seq TO authenticated;

REVOKE ALL ON public.system_secrets FROM anon, authenticated;

DO $$
BEGIN
  PERFORM cron.unschedule('agromotor-hydric-daily');
EXCEPTION WHEN OTHERS THEN
  NULL;
END $$;

SELECT cron.schedule(
  'agromotor-hydric-daily',
  '15 8 * * *',
  $cron$
    SELECT net.http_post(
      url := 'https://xsbaqlqztppdpdcjgazz.supabase.co/functions/v1/hydric-daily',
      headers := jsonb_build_object(
        'Content-Type', 'application/json',
        'x-cron-token', (
          SELECT secret_value
          FROM public.system_secrets
          WHERE key = 'hydric_cron_token'
        )
      ),
      body := jsonb_build_object('scheduled_at', now()),
      timeout_milliseconds := 120000
    );
  $cron$
);
